<?php

namespace Database\Seeders;

use App\Models\PosHunterSentence;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PosHunterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sentences = [
            ['difficulty' => 'easy', 'sentence' => 'The dog barked loudly.'],
            ['difficulty' => 'easy', 'sentence' => 'She drank water.'],
            ['difficulty' => 'easy', 'sentence' => 'He reads books daily.'],
            ['difficulty' => 'easy', 'sentence' => 'Birds fly high.'],
            ['difficulty' => 'easy', 'sentence' => 'The sun shines brightly.'],
            ['difficulty' => 'easy', 'sentence' => 'They play soccer.'],
            ['difficulty' => 'easy', 'sentence' => 'She likes flowers.'],
            ['difficulty' => 'easy', 'sentence' => 'The baby sleeps quietly.'],
            ['difficulty' => 'easy', 'sentence' => 'He eats apples.'],
            ['difficulty' => 'easy', 'sentence' => 'Fish swim in water.'],
            ['difficulty' => 'easy', 'sentence' => 'She sings beautifully.'],
            ['difficulty' => 'easy', 'sentence' => 'The wind blows softly.'],
            ['difficulty' => 'easy', 'sentence' => 'They watch movies.'],
            ['difficulty' => 'easy', 'sentence' => 'The cat sleeps often.'],
            ['difficulty' => 'easy', 'sentence' => 'She reads stories.'],
            ['difficulty' => 'easy', 'sentence' => 'The sky is blue.'],
            ['difficulty' => 'easy', 'sentence' => 'He walks daily.'],
            ['difficulty' => 'easy', 'sentence' => 'The trees are tall.'],
            ['difficulty' => 'easy', 'sentence' => 'They ride bikes.'],
            ['difficulty' => 'easy', 'sentence' => 'He plays guitar.'],
            ['difficulty' => 'easy', 'sentence' => 'She swims fast.'],
            ['difficulty' => 'easy', 'sentence' => 'The leaves are green.'],
            ['difficulty' => 'easy', 'sentence' => 'The dog wags its tail.'],
            ['difficulty' => 'easy', 'sentence' => 'She draws pictures.'],
            ['difficulty' => 'easy', 'sentence' => 'The car is red.'],
            ['difficulty' => 'easy', 'sentence' => 'They jump high.'],
            ['difficulty' => 'easy', 'sentence' => 'The cat purrs softly.'],
            ['difficulty' => 'easy', 'sentence' => 'He runs fast.'],
            ['difficulty' => 'easy', 'sentence' => 'She paints well.'],
            ['difficulty' => 'easy', 'sentence' => 'They laugh loudly.'],
            ['difficulty' => 'easy', 'sentence' => 'The cake smells good.'],
            ['difficulty' => 'easy', 'sentence' => 'She skips happily.'],
            ['difficulty' => 'easy', 'sentence' => 'He listens carefully.'],
            ['difficulty' => 'easy', 'sentence' => 'The grass is green.'],
            ['difficulty' => 'easy', 'sentence' => 'They clap loudly.'],
            ['difficulty' => 'easy', 'sentence' => 'The child smiles brightly.'],
            ['difficulty' => 'easy', 'sentence' => 'She dances gracefully.'],
            ['difficulty' => 'easy', 'sentence' => 'The door is open.'],
            ['difficulty' => 'easy', 'sentence' => 'They eat together.'],
            ['difficulty' => 'easy', 'sentence' => 'He laughs often.'],
            ['difficulty' => 'easy', 'sentence' => 'The book is old.'],
            ['difficulty' => 'easy', 'sentence' => 'She cooks dinner.'],
            ['difficulty' => 'easy', 'sentence' => 'The table is clean.'],
            ['difficulty' => 'easy', 'sentence' => 'They drive slowly.'],
            ['difficulty' => 'easy', 'sentence' => 'The bird sings sweetly.'],
            ['difficulty' => 'easy', 'sentence' => 'He talks calmly.'],
            ['difficulty' => 'easy', 'sentence' => 'She walks quickly.'],
            ['difficulty' => 'easy', 'sentence' => 'The fish are small.'],
            ['difficulty' => 'easy', 'sentence' => 'They dance together.'],
            ['difficulty' => 'easy', 'sentence' => 'He writes neatly.'],
            ['difficulty' => 'easy', 'sentence' => 'The house is big.'],
            ['difficulty' => 'easy', 'sentence' => 'She knits scarves.'],
            ['difficulty' => 'easy', 'sentence' => 'They talk softly.'],
            ['difficulty' => 'easy', 'sentence' => 'The chair is broken.'],
            ['difficulty' => 'easy', 'sentence' => 'She draws flowers.'],
            ['difficulty' => 'easy', 'sentence' => 'The apple is red.'],
            ['difficulty' => 'easy', 'sentence' => 'They hike often.'],
            ['difficulty' => 'easy', 'sentence' => 'He works hard.'],
            ['difficulty' => 'easy', 'sentence' => 'The boy is tall.'],
            ['difficulty' => 'easy', 'sentence' => 'She whispers softly.'],
            ['difficulty' => 'easy', 'sentence' => 'The cake is sweet.'],
            ['difficulty' => 'easy', 'sentence' => 'He listens quietly.'],
            ['difficulty' => 'easy', 'sentence' => 'They laugh together.'],
            ['difficulty' => 'easy', 'sentence' => 'The cat is soft.'],
            ['difficulty' => 'easy', 'sentence' => 'She bakes cookies.'],
            ['difficulty' => 'easy', 'sentence' => 'The dog is playful.'],
            ['difficulty' => 'easy', 'sentence' => 'They swim together.'],
            ['difficulty' => 'easy', 'sentence' => 'He cleans the car.'],
            ['difficulty' => 'easy', 'sentence' => 'The lamp is bright.'],
            ['difficulty' => 'easy', 'sentence' => 'She reads books.'],
            ['difficulty' => 'easy', 'sentence' => 'The soup is hot.'],
            ['difficulty' => 'easy', 'sentence' => 'He sings songs.'],
            ['difficulty' => 'easy', 'sentence' => 'The plant grows tall.'],
            ['difficulty' => 'easy', 'sentence' => 'She writes stories.'],
            ['difficulty' => 'easy', 'sentence' => 'The car is fast.'],
            ['difficulty' => 'easy', 'sentence' => 'They walk slowly.'],
            ['difficulty' => 'easy', 'sentence' => 'The flower smells nice.'],
            ['difficulty' => 'easy', 'sentence' => 'She knits blankets.'],
            ['difficulty' => 'easy', 'sentence' => 'The floor is clean.'],
            ['difficulty' => 'easy', 'sentence' => 'They laugh loudly.'],
            ['difficulty' => 'easy', 'sentence' => 'The room is dark.'],
            ['difficulty' => 'easy', 'sentence' => 'She dances well.'],
            ['difficulty' => 'easy', 'sentence' => 'He drinks milk.'],
            ['difficulty' => 'easy', 'sentence' => 'The tree is tall.'],
            ['difficulty' => 'easy', 'sentence' => 'She smiles brightly.'],
            ['difficulty' => 'easy', 'sentence' => 'The baby is asleep.'],
            ['difficulty' => 'easy', 'sentence' => 'He runs quickly.'],
            ['difficulty' => 'easy', 'sentence' => 'The boat floats.'],
            ['difficulty' => 'easy', 'sentence' => 'She draws animals.'],
            ['difficulty' => 'easy', 'sentence' => 'The snow is white.'],
            ['difficulty' => 'easy', 'sentence' => 'He likes movies.'],
            ['difficulty' => 'easy', 'sentence' => 'The cheese is tasty.'],
            ['difficulty' => 'easy', 'sentence' => 'She enjoys music.'],
            ['difficulty' => 'easy', 'sentence' => 'They eat pizza.'],
            ['difficulty' => 'easy', 'sentence' => 'The fire burns bright.'],
            ['difficulty' => 'easy', 'sentence' => 'He climbs trees.'],
            ['difficulty' => 'easy', 'sentence' => 'The sky is clear.'],
            ['difficulty' => 'easy', 'sentence' => 'She drives fast.'],
            ['difficulty' => 'easy', 'sentence' => 'The milk is cold.'],
            ['difficulty' => 'easy', 'sentence' => 'They watch sports.'],
            ['difficulty' => 'easy', 'sentence' => 'He draws cars.'],
            ['difficulty' => 'easy', 'sentence' => 'The cat is fluffy.'],
        ];
        foreach ($sentences as $sentence) {
            PosHunterSentence::create($sentence);
        }
    }
}
